steps:
  # Build Core Service para Staging
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/xafra-ads/xafra-ads/core-service-stg:latest'
      - '-f'
      - 'deployment/Dockerfile.core-service'
      - '.'

  # Deploy a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'core-service-stg'
      - '--image'
      - 'us-central1-docker.pkg.dev/xafra-ads/xafra-ads/core-service-stg:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=staging,DATABASE_URL=postgresql://postgres:XafraTech2025!@34.28.245.62:5432/xafra-ads?schema=staging,REDIS_URL=redis://10.147.230.83:6379,ENCRYPTION_KEY=stg-256-bit-encryption-key-for-staging-environment-testing,POSTBACK_SERVICE_URL=https://postback-service-stg-697203931362.us-central1.run.app/api/postbacks/send'

images:
  - 'us-central1-docker.pkg.dev/xafra-ads/xafra-ads/core-service-stg:latest'

timeout: '1200s'