# 🚀 Cloud Build específico para Core Service
steps:
  # Build de la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'deployment/Dockerfile.core-service'
      - '-t'
      - 'us-central1-docker.pkg.dev/xafra-ads/xafra-ads/core-service-stg:latest'
      - '.'

  # Push de la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/xafra-ads/xafra-ads/core-service-stg:latest'

  # Deploy a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'core-service-stg'
      - '--image'
      - 'us-central1-docker.pkg.dev/xafra-ads/xafra-ads/core-service-stg:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=staging,DATABASE_URL=postgresql://postgres:XafraTech2025!@34.28.245.62:5432/xafra-ads?schema=staging,REDIS_URL=redis://10.147.230.83:6379,ENCRYPTION_KEY=stg-256-bit-encryption-key-for-staging-environment-testing'
      - '--timeout'
      - '300'

# Especificar imágenes para el registry
images:
  - 'us-central1-docker.pkg.dev/xafra-ads/xafra-ads/core-service-stg:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'